apiVersion: v1
kind: Pod
metadata:
  name: test-pod-myscheduler
  labels:
    name: myscheduler-pod-example
spec:
  schedulerName: myscheduler
  containers:
  - name: pod-scheduled-by-myscheduler
    image: k8s.gcr.io/pause:2.0

