apiVersion: v1
kind: Pod
metadata:
  name: test-pod-myscheduler
  labels:
    name: multischeduler-example
spec:
  schedulerName: myscheduler
  containers:
  - name: pod-with-second-annotation-container
    image: k8s.gcr.io/pause:2.0

